[package]
name = "ecies-encryption-cli"
version = "0.1.0"
edition = "2024"
description = "Demo usage of ecies-encryption-lib"

[dependencies]
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }

ecies-encryption-lib = { workspace = true }
